import js from "@eslint/js";
import prettier from "eslint-config-prettier/flat";
import globals from "globals";
import tseslint from "typescript-eslint";

/**
 * Shared flat-config base for every workspace package.
 *
 * Each package re-exports this from its own `eslint.config.js` so that
 * `turbo lint` can run `eslint` with the package as the working directory.
 * Package-specific layers (e.g. Svelte in `apps/web`) are appended there.
 *
 * `prettier` must stay last: it switches off the stylistic rules that
 * Prettier owns.
 */
export default tseslint.config(
	{
		ignores: [
			"**/node_modules/**",
			"**/dist/**",
			"**/build/**",
			"**/coverage/**",
			"**/.turbo/**",
			"**/.svelte-kit/**",
			"**/generated/**",
			// Autogenerated by varlock.
			"**/env.d.ts",
		],
	},
	js.configs.recommended,
	tseslint.configs.recommended,
	{
		languageOptions: {
			globals: { ...globals.node },
		},
		rules: {
			// Underscore-prefixed bindings are the conventional "intentionally
			// unused" marker (unused route params, discarded destructured fields).
			"@typescript-eslint/no-unused-vars": [
				"error",
				{
					argsIgnorePattern: "^_",
					varsIgnorePattern: "^_",
					caughtErrorsIgnorePattern: "^_",
				},
			],
		},
	},
	prettier,
);
